### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by vilvo**

### CODE REVIEW

**Comment by vilvo** [comment]
@brianmcgillion Apache 2.0 based on your input. Please review and merge at your leisure.

**Comment by henrirosten** [comment]
@vilvo : thanks for the PR!
sbomnix uses [reuse lint](https://github.com/tiiuae/sbomnix/blob/e926759e755f2724b69bc6b75f3f01e628fde961/Makefile#L41) 
 to maintain compliance with [reuse](https://reuse.software/).

If it's fine for you, I'll fix this PR to maintain reuse compliance, changing the license to Apache 2.0.

**Comment by vilvo** [comment]
> @vilvo : thanks for the PR! sbomnix uses [reuse lint](https://github.com/tiiuae/sbomnix/blob/e926759e755f2724b69bc6b75f3f01e628fde961/Makefile#L41) to maintain compliance with [reuse](https://reuse.software/).
> 
> If it's fine for you, I'll fix this PR to maintain reuse compliance, changing the license to Apache 2.0. Should we also change the copyright owner?

Thanks. Feel free to add commits to fix the reuse compliance.

**Comment by henrirosten** [comment]
@vilvo, @brianmcgillion: please check https://github.com/tiiuae/sbomnix/pull/1/commits/fd558b92ed5447a25c29a1b711f0eaf5fdd29917. I'll merge this PR if you are also fine with the license and copyright owner after that change.

**Comment by vilvo** [comment]
> @vilvo, @brianmcgillion: please check [fd558b9](https://github.com/tiiuae/sbomnix/commit/fd558b92ed5447a25c29a1b711f0eaf5fdd29917). I'll merge this PR if you are also fine with the license and copyright owner after that change.

Thanks, fine by me. Can't add a review since I opened the PR.

**Review by henrirosten — APPROVED** [review]

**Comment by henrirosten** [comment]
@brianmcgillion : I'll merge this by the end of day today unless you disagree before that.

**Pull request merged**
